version: "3"
services:
  bst:
    image: php:8.2-cli
    working_dir: /home
    volumes:
      - ./:/home/
    entrypoint: php cli/bst.php
  search:
    image: php:8.2-cli
    working_dir: /home
    volumes:
      - ./:/home/
    entrypoint: php cli/search.php
  functional-tests:
    build:
      context: .
      dockerfile: docker/functional-tests/Dockerfile
